### ISSUE TITLE
Which Ruby version?

### ISSUE THREAD

**Issue by roytomeij** [turingschool/turing.io#12]
The readme tells me to use Ruby `2.1.4`, the `.ruby-version` file says `2.1.3`, and the `Gemfile` says `2.2.1`. I updated it in #13.

**Comment by jcasimir** [comment]
Yes, 2.2.1. Sorry for the errors.

**Comment by roytomeij** [comment]
No prob @jcasimir, just updated this issue to point to the changes I made in a PR to use 2.2.1 across the board. Closing this one.
